theme: jekyll-theme-minimal
title: MPEDS - Automated Coding of Protest Event Data
description: Machine-Learning Protest Event Data System
show_downloads: true

# include these as manual settings to avoid linking to website

repository_url: https://github.com/mpeds/mpeds/
zip_url: https://github.com/mpeds/mpeds/archive/master.zip
tar_url: https://github.com/mpeds/mpeds/archive/master.tar.gz

navigation:

  - title: Quick Start
    url: quickstart.html

  - title: Publications
    url: publications.html

  - title: Annotation Interface
    url: mai.html